-- Enable PostGIS extension
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;

-- Grant permissions to riffai user
GRANT ALL PRIVILEGES ON DATABASE riffai TO riffai;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO riffai;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO riffai;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO riffai;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO riffai;
